development:
  secret_key_base: <%= ENV["DEVELOPMENT_SECRET_KEY_BASE"] %>
  embedly_api_key: <%= ENV["EMBEDLY_KEY"] %>
test:
  secret_key_base: <%= ENV["TEST_SECRET_KEY_BASE"] %>
production:
  secret_key_base: <%= ENV["PRODUCTION_SECRET_KEY_BASE"] %>
  embedly_api_key: <%= ENV["EMBEDLY_KEY"] %>